import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--var(montserrat)",
});

export const metadata: Metadata = {
  title: "Agência de Viagens Online com Descontos HOJE | Decolar",
  description:
    "Planeje sua viagem com a Decolar, a maior agência de viagens online do Brasil. Monte o seu pacote de viagem e tire todas as suas dúvidas conosco!",
  keywords: [
    "Decolar",
    "Viagens aéreas",
    "Descontos em voos",
    "Passagens aéreas baratas",
    "Promoções de voos",
    "Ofertas de viagens",
    "Bilhetes de avião com desconto",
    "Reservas de voos online",
    "Comparação de preços de voos",
    "Tarifas aéreas reduzidas",
    "Voos com preços especiais",
    "Economize em passagens aéreas",
    "Voe por menos",
    "Agência de viagens online",
    "Planejamento de viagens",
    "Destinos econômicos",
    "Voos econômicos",
    "Pacotes de viagem com desconto",
    "Ofertas exclusivas de voos",
    "Descontos de última hora em voos",
    "Tarifas especiais em passagens aéreas",
    "Passagens aéreas em promoção",
    "Voos com tarifas reduzidas",
    "Economia em voos internacionais",
    "Descontos em voos domésticos",
    "Viagens acessíveis",
    "Passagens aéreas em oferta",
    "Melhores tarifas aéreas",
    "Voos de baixo custo",
    "Planeje sua viagem com desconto",
    "Agente de viagens online",
    "Descontos de temporada em voos",
    "Tarifas reduzidas para destinos populares",
    "Viagens econômicas de avião",
    "Bilhetes com preço reduzido",
    "Viagens de última hora",
    "Tarifas especiais para voos internacionais",
    "Promoções em voos nacionais",
    "Voos para férias com desconto",
    "Economia em voos de negócios",
    "Tarifas reduzidas para voos familiares",
    "Reservas de voos baratos",
    "Viagens com desconto para grupos",
    "Economize em passagens de avião",
    "Promoções de voos de ida e volta",
    "Voos com desconto para estudantes",
    "Tarifas reduzidas para viagens corporativas",
    "Ofertas de voos de final de semana",
    "Passagens aéreas em liquidação",
    "Viagens de avião acessíveis",
    "Voos promocionais",
    "Descontos em voos internacionais",
    "Tarifas aéreas com desconto",
    "Voos para destinos exóticos",
    "Economize em voos de lua de mel",
    "Promoções de voos de feriados",
    "Voos com desconto de aniversário",
    "Tarifas reduzidas para voos de lua de mel",
    "Passagens aéreas de última hora",
    "Viagens de fim de semana com desconto",
    "Tarifas especiais em voos de negócios",
    "Voos com desconto para aposentados",
    "Promoções em voos para grupos",
    "Viagens econômicas de última hora",
    "Descontos em voos para eventos especiais",
    "Tarifas reduzidas para voos de réveillon",
    "Passagens aéreas com desconto para feriados prolongados",
    "Economize em voos de aniversário de casamento",
    "Promoções em voos de fim de semana prolongado",
    "Voos com desconto para destinos de lua de mel",
    "Tarifas especiais para voos de fim de semana",
    "Passagens aéreas com desconto para feriados religiosos",
    "Economia em voos de eventos esportivos",
    "Descontos em voos para festivais",
    "Viagens econômicas para o Carnaval",
    "Tarifas reduzidas para voos de conferências",
    "Passagens aéreas com desconto para viagens em grupo",
    "Economize em voos de excursão",
    "Promoções em voos de formatura",
    "Voos com desconto para festas de fim de ano",
    "Descontos em voos de cruzeiro",
    "Tarifas reduzidas para viagens de voluntariado",
    "Passagens aéreas com desconto para viagens de estudo",
    "Economia em voos de intercâmbio",
    "Promoções em voos de imersão cultural",
    "Viagens econômicas de aniversário de empresa",
    "Descontos em voos para viagens de aventura",
    "Tarifas reduzidas para voos de turismo religioso",
    "Passagens aéreas com desconto para viagens de negócios",
    "Economize em voos de feiras comerciais",
    "Promoções em voos de treinamento corporativo",
    "Voos com desconto para feiras de exposição",
    "Descontos em voos para viagens de incentivo",
    "Tarifas reduzidas para viagens de pesquisa",
    "Passagens aéreas com desconto para expedições",
    "Economia em voos para viagens de reconhecimento",
    "Promoções em voos de estudo de campo",
    "Viagens econômicas para conferências médicas",
    "Descontos em voos para eventos culturais",
    "Tarifas reduzidas para viagens de turismo médico",
    "Passagens aéreas com desconto para feiras de tecnologia",
    "Economize em voos de exposições científicas",
    "Promoções em voos para conferências de TI",
    "Voos com desconto para eventos gastronômicos",
    "Descontos em voos para festivais de música",
    "Tarifas reduzidas para viagens de conferências educacionais",
    "Passagens aéreas com desconto para festivais de cinema",
    "Economia em voos para eventos de moda",
    "Promoções em voos para convenções de negócios",
    "Viagens econômicas para festivais de arte",
    "Descontos em voos para competições esportivas",
    "Tarifas reduzidas para eventos de entretenimento",
    "Passagens aéreas com desconto para feiras de beleza",
    "Economize em voos para exposições agrícolas",
    "Promoções em voos para festivais de vinho",
    "Voos com desconto para eventos de tecnologia",
    "Descontos em voos para exposições automotivas",
    "Tarifas reduzidas para feiras de franquias",
    "Passagens aéreas com desconto para convenções de saúde",
    "Economia em voos para exposições de arte",
    "Promoções em voos para eventos de turismo",
    "Viagens econômicas para feiras de negócios",
    "Descontos em voos para eventos de decoração",
    "Tarifas reduzidas para festivais de cerveja",
    "Passagens aéreas com desconto para festivais de comédia",
    "Economize em voos para convenções de software",
    "Promoções em voos para festivais religiosos",
    "Voos com desconto para feiras de alimentos",
    "Descontos em voos para feiras de casamento",
    "Tarifas reduzidas para eventos de design",
    "Passagens aéreas com desconto para conferências de marketing",
    "Economia em voos para exposições de construção",
    "Promoções em voos para festivais de literatura",
    "Viagens econômicas para eventos de aviação",
    "Descontos em voos para feiras de brinquedos",
    "Tarifas reduzidas para conferências de segurança",
    "Passagens aéreas com desconto para festivais de dança",
    "Economize em voos para exposições de petróleo e gás",
    "Promoções em voos para eventos de tecnologia limpa",
    "Voos com desconto para feiras de negócios internacionais",
    "Descontos em voos para eventos de mineração",
    "Tarifas reduzidas para conferências de educação",
    "Passagens aéreas com desconto para feiras de bricolagem",
    "Economia em voos para exposições de energia renovável",
    "Promoções em voos para festivais de fotografia",
    "Viagens econômicas para conferências de mídia",
    "Descontos em voos para feiras de moda",
    "Tarifas reduzidas para eventos de entretenimento ao ar livre",
    "Passagens aéreas com desconto para festivais de cerveja",
    "Economize em voos para exposições de moda",
    "Promoções em voos para eventos de tecnologia espacial",
    "Voos com desconto para feiras de animais de estimação",
    "Descontos em voos para conferências de transporte",
    "Tarifas reduzidas para festivais de comidas e bebidas",
    "Passagens aéreas com desconto para feiras de saúde e fitness",
    "Economia em voos para exposições de arte contemporânea",
    "Promoções em voos para festivais de cinema independente",
    "Viagens econômicas para conferências de arquitetura",
    "Descontos em voos para feiras de viagens e turismo",
    "Tarifas reduzidas para eventos de tecnologia blockchain",
    "Passagens aéreas com desconto para festivais de teatro",
    "Economize em voos para exposições de robótica",
    "Promoções em voos para eventos de fintech",
    "Voos com desconto para feiras de saúde mental",
    "Descontos em voos para conferências de ciência de dados",
    "Tarifas reduzidas para festivais de música clássica",
    "Passagens aéreas com desconto para feiras de estilo de vida",
    "Economia em voos para exposições de design de interiores",
    "Promoções em voos para eventos de tecnologia de IA",
    "Viagens econômicas para conferências de saúde pública",
    "Descontos em voos para feiras de jardinagem",
    "Tarifas reduzidas para festivais de jogos",
    "Passagens aéreas com desconto para feiras de alimentação saudável",
    "Economize em voos para exposições de arte moderna",
    "Promoções em voos para eventos de realidade virtual",
    "Voos com desconto para feiras de saúde e bem-estar",
    "Descontos em voos para conferências de inteligência emocional",
    "Tarifas reduzidas para festivais de comédia stand-up",
    "Passagens aéreas com desconto para feiras de segurança cibernética",
    "Economia em voos para exposições de ciências naturais",
    "Promoções em voos para eventos de tecnologia de nuvem",
    "Viagens econômicas para conferências de economia sustentável",
    "Descontos em voos para feiras de empreendedorismo",
    "Tarifas reduzidas para festivais de música eletrônica",
    "Passagens aéreas com desconto para feiras de sustentabilidade",
    "Economize em voos para exposições de história",
    "Promoções em voos para eventos de realidade aumentada",
    "Voos com desconto para feiras de moda ética",
    "Descontos em voos para conferências de liderança",
    "Tarifas reduzidas para festivais de cinema de terror",
    "Passagens aéreas com desconto para feiras de carreira",
    "Economia em voos para exposições de arte abstrata",
    "Promoções em voos para eventos de tecnologia móvel",
    "Viagens econômicas para conferências de psicologia",
    "Descontos em voos para feiras de recursos humanos",
    "Tarifas reduzidas para festivais de música alternativa",
    "Passagens aéreas com desconto para feiras de coaching",
    "Economize em voos para exposições de moda sustentável",
    "Promoções em voos para eventos de tecnologia educacional",
    "Voos com desconto para feiras de desenvolvimento pessoal",
  ],
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "/",
    title: "Agência de Viagens Online com Descontos HOJE | Decolar",
    description:
      "Planeje sua viagem com a Decolar, a maior agência de viagens online do Brasil. Monte o seu pacote de viagem e tire todas as suas dúvidas conosco!",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} ${montserrat.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
